version: '3.3'

volumes:
    postgres:

services:
  db:
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "holaplex"
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
    ports:
      - "15432:5432"
    restart: unless-stopped
